<html>
    <head>
    <link rel="stylesheet" href="http://localhost/project/style.css"></head>
    <body>
        <header><h1>TERMS AND CONDITIONS</h1></header>

<h1>I AM AGREEING TO FOLLOWING CONDITIONS:</H1><br><hr>
<h3>1. I WILL NOT HARASS ANY JOBSEEKER.<br>
2. I WILL NOT DUPLICATE MY IDENTITY.<br>
3. IF I AM  HIRING SOMEONE I WILL PAY THEM THEIR SALARY ON TIME.<br>
4. I(EMPLOYER) AM SUPPOSE TO DO THEIR VALIDATION BY CHECKING THEIR IDENTITY CARDS AFTER I HIRE THEM. BUT I WILL NOT MISUSE THOSE DETAILS.<br>
5. I WILL RESPECT THEIR PRIVACY AND I ACCEPT ALL THE TERMS AND CONDITONS REGARDING PRIVACY WHICH ARE MADE IN FUTURE.
IF I DO ANY OF THE ABOVE MENTIONED ACTS I AM SUPPOSED TO GO THROUGH LEAGAL ACTIONS TAKEN BY FMO OR THAT JOBSEEKER<br><hr>
</h3></body></html>